/* Generated by fxsh */
#include <stdbool.h>
#include <stdint.h>

/* Type aliases */
typedef int64_t s64;
typedef int32_t s32;
typedef int16_t s16;
typedef int8_t s8;
typedef uint64_t u64;
typedef uint32_t u32;
typedef uint16_t u16;
typedef uint8_t u8;
typedef float f32;
typedef double f64;
typedef char c8;

/* ADT Type Definitions */

/* ADT type definition */
typedef enum {
  fxsh_tag_option_None,
  fxsh_tag_option_Some
} fxsh_tag_option_t;

typedef union {
  struct {
    s64 _0;
  } Some;
} fxsh_data_option_t;

typedef struct {
  fxsh_tag_option_t tag;
  fxsh_data_option_t data;
} fxsh_option_t;

static fxsh_option_t fxsh_constr_None(void) {
  fxsh_option_t val;
  val.tag = fxsh_tag_option_None;
  return val;
}

static fxsh_option_t fxsh_constr_Some(s64 arg0) {
  fxsh_option_t val;
  val.tag = fxsh_tag_option_Some;
  val.data.Some._0 = arg0;
  return val;
}

/* Forward declarations */


static fxsh_option_t x;
/* expr */
/* Runtime initialization for ADT values */
static void fxsh_init_adt_values(void) {
  x = fxsh_constr_Some(42);
}

/* Main entry point */
int main(void) {
  fxsh_init_adt_values();
  return 0;
}


