/* Generated by fxsh */
#include <stdbool.h>
#include <stdint.h>

/* Type aliases */
typedef int64_t s64;
typedef int32_t s32;
typedef int16_t s16;
typedef int8_t s8;
typedef uint64_t u64;
typedef uint32_t u32;
typedef uint16_t u16;
typedef uint8_t u8;
typedef float f32;
typedef double f64;
typedef char c8;

/* ADT Type Definitions */

/* ADT type definition */
typedef enum {
  fxsh_tag_list_Nil,
  fxsh_tag_list_Cons
} fxsh_tag_list_t;

typedef struct fxsh_list fxsh_list_t;

typedef union {
  struct {
    s64 _0;
    fxsh_list_t _1;
  } Cons;
} fxsh_data_list_t;

struct fxsh_list {
  fxsh_tag_list_t tag;
  fxsh_data_list_t data;
};

static fxsh_list_t fxsh_constr_Nil(void) {
  fxsh_list_t val;
  val.tag = fxsh_tag_list_Nil;
  return val;
}

static fxsh_list_t fxsh_constr_Cons(s64 arg0, fxsh_list_t arg1) {
  fxsh_list_t val;
  val.tag = fxsh_tag_list_Cons;
  val.data.Cons._0 = arg0;
  val.data.Cons._1 = arg1;
  return val;
}

/* Forward declarations */


static fxsh_list_t x;
/* expr */
/* Runtime initialization for ADT values */
static void fxsh_init_adt_values(void) {
  x = fxsh_constr_Cons(42, fxsh_constr_Nil());
}

/* Main entry point */
int main(void) {
  fxsh_init_adt_values();
  return 0;
}


